# encoding: UTF-8															
# This file should contain all the record creation needed to seed the database with its default values.															
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).															
#															
# Examples:															
#															
#   cities = City.create([{ name: 	Chicago	 }, { name: 	Copenhagen	 }])											
#   Mayor.create(name: 	Emanuel	, city: cities.first)													
															
Product.delete_all																
Product.create(name:'BEARING STD MOD 06D',code:'BOC-1820',marc:'Carrier',quantity:100,price:1.0,imageurl:'bocina/Carrier_bocina/06D_1820_1821_1822.jpg',model:'06D',flagmis:'no')
Product.create(name:'BEARING - MOTOR SIDE STD MOD 06E',code:'BOC-3011',marc:'Carrier',quantity:100,price:15.13,imageurl:'bocina/Carrier_bocina/06E_3011_3012_3013_3014_3015_3016.jpg',model:'06E LADO MOTOR',flagmis:'no')
Product.create(name:'TERMINAL KIT - 9 TERMINALS MOD 06E',code:'KIT-1673',marc:'Carrier',quantity:100,price:106.0,imageurl:'KIT_BORNERA_CARRIER/KIT-1673.gif',model:'06E',flagmis:'no')
Product.create(name:'PISTON PIN MOD 06E',code:'PAS-1951',marc:'Carrier',quantity:100,price:3.0,imageurl:'PASADOR_CARRIER/PAS-1951.gif',model:'06E',flagmis:'no')
Product.create(name:'PISTON STD MOD 06DA337',code:'PIS-1825',marc:'Carrier',quantity:100,price:18.0,imageurl:'piston/Carrier_piston/1825.jpg',model:'06DA337',flagmis:'no')
Product.create(name:'PISTON - TWO STEP CONTOURED TOP STD MOD 06E 265',code:'PIS-1895',marc:'Carrier',quantity:100,price:18.0,imageurl:'piston/Carrier_piston/1897_1898_1895_1896.jpg',model:'06E 265',flagmis:'no')
Product.create(name:'PISTON - TWO STEP CONTOURED TOP STD MOD 06E250/06E275/06E299',code:'PIS-1897',marc:'Carrier',quantity:100,price:18.0,imageurl:'piston/Carrier_piston/1897_1898_1895_1896.jpg',model:'06E250/06E275/06E299',flagmis:'no')
Product.create(name:'PISTON STD MOD 06DA537',code:'PIS-1946',marc:'Carrier',quantity:100,price:1.0,imageurl:'piston/Carrier_piston/1946.jpg',model:'06DA537',flagmis:'no')
Product.create(name:'PISTON STD MOD 06DA824',code:'PIS-1973',marc:'Carrier',quantity:100,price:16.0,imageurl:'piston/Carrier_piston/1973.jpg',model:'06DA824',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD MRA/MRF',code:'ANI-2303',marc:'Copeland',quantity:100,price:2.26,imageurl:'ANILLOS_COPELND_PHOTO/ANI-2303.gif',model:'MRA/MRF',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 2DA/MRH',code:'ANI-2305',marc:'Copeland',quantity:100,price:2.26,imageurl:'logo/no_dispo.jpg',model:'2DA/MRH',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 9RS/9RT/9TH/LAC/LAM/NRD',code:'ANI-2307',marc:'Copeland',quantity:100,price:2.16,imageurl:'ANILLOS_COPELND_PHOTO/ANI-2307.gif',model:'9RS/9RT/9TH/LAC/LAM/NRD',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 2DD/2DL/4DA/4DE/4DN',code:'ANI-2308',marc:'Copeland',quantity:100,price:2.32,imageurl:'ANILLOS_COPELND_PHOTO/ANI-2308.gif',model:'2DD/2DL/4DA/4DE/4DN',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 4RH/6RH/4RK/4RL/6RP/6TM',code:'ANI-2318',marc:'Copeland',quantity:100,price:2.58,imageurl:'ANILLOS_COPELND_PHOTO/ANI-2318.gif',model:'4RH/6RH/4RK/4RL/6RP/6TM',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 4RH/6RH/4RK/6RK/4RL/6RL/4RP/6RP/4',code:'ANI-2319',marc:'Copeland',quantity:100,price:2.14,imageurl:'ANILLOS_COPELND_PHOTO/ANI-2319.gif',model:'4RH/6RH/4RK/6RK/4RL/6RL/4RP/6RP/4',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 4D/6D/4RR/4RJ/6RS/6RJ',code:'ANI-2389',marc:'Copeland',quantity:100,price:2.26,imageurl:'ANILLOS_COPELND_PHOTO/ANI-2389.gif',model:'4D/6D/4RR/4RJ/6RS/6RJ',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 9RB/RC/RP/TL/LAL',code:'ANI-2405',marc:'Copeland',quantity:100,price:2.26,imageurl:'ANILLOS_COPELND_PHOTO/ANI-2405.gif',model:'9RB/RC/RP/TL/LAL',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 3RA/9RA/9RJ/NRM/NRN/3DA/3DE',code:'ANI-7194',marc:'Copeland',quantity:100,price:3.12,imageurl:'ANILLOS_COPELND_PHOTO/ANI-7194.gif',model:'3RA/9RA/9RJ/NRM/NRN/3DA/3DE',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 3RK/3DF/3DG/3DK',code:'ANI-7244',marc:'Copeland',quantity:100,price:2.26,imageurl:'ANILLOS_COPELND_PHOTO/ANI-7244.gif',model:'3RK/3DF/3DG/3DK FINO',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 3DB/DJ/DP/LAL/9RB/9RC',code:'ANI-7254',marc:'Copeland',quantity:100,price:2.26,imageurl:'ANILLOS_COPELND_PHOTO/ANI-7254.gif',model:'3DB/DJ/DP/LAL/9RB/9RC',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 3DR/3DS/3DT/LAC/LAM/NRA/NRD/NRL/N',code:'ANI-7264',marc:'Copeland',quantity:100,price:2.26,imageurl:'ANILLOS_COPELND_PHOTO/ANI-7264.gif',model:'3DR/3DS/3DT/LAC/LAM/NRA/NRD/NRL/N',flagmis:'no')
Product.create(name:'PISTON RING - COMPRESSION STD MOD 2DB/MRB',code:'ANI-7334',marc:'Copeland',quantity:100,price:2.26,imageurl:'ANILLOS_COPELND_PHOTO/ANI-7334.gif',model:'2DB/ MRB',flagmis:'no')
Product.create(name:'BEARING - PUMP SIDE NEW STYLE STD MOD 9D/9R',code:'BOC-1332',marc:'Copeland',quantity:100,price:23.0,imageurl:'bocina/Copeland_bocina/1332_9R.jpg',model:'9D/9R LADO BOMBA NEW STYLE',flagmis:'no')
Product.create(name:'BEARING STD  MOD 3R',code:'BOC-1346',marc:'Copeland',quantity:100,price:8.0,imageurl:'bocina/Copeland_bocina/1346_3R_3A_L_E_1546.jpg',model:'3R',flagmis:'no')
Product.create(name:'BEARING STD MOD H',code:'BOC-1347',marc:'Copeland',quantity:100,price:5.38,imageurl:'bocina/Copeland_bocina/1347_H_K.jpg',model:'H',flagmis:'no')
Product.create(name:'BEARING - PISTON SIDE STD MOD M',code:'BOC-1348',marc:'Copeland',quantity:100,price:17.0,imageurl:'bocina/Copeland_bocina/1348_M.jpg',model:'M LADO PISTON',flagmis:'no')
Product.create(name:'BEARING - MOTOR SIDE STD MOD M',code:'BOC-1349',marc:'Copeland',quantity:100,price:14.0,imageurl:'bocina/Copeland_bocina/1348_M.jpg',model:'M LADO MOTOR',flagmis:'no')
Product.create(name:'BEARING - PUMP SIDE STD MOD M',code:'BOC-1350',marc:'Copeland',quantity:100,price:24.0,imageurl:'bocina/Copeland_bocina/1348_M.jpg',model:'M LADO BOMBA',flagmis:'no')
Product.create(name:'BEARING - PISTON SIDE STD MOD 9R',code:'BOC-1351',marc:'Copeland',quantity:100,price:17.0,imageurl:'bocina/Copeland_bocina/1351_9R.jpg',model:'9R LADO PISTON',flagmis:'no')
Product.create(name:'BEARING - MOTOR SIDE STD MOD 9R',code:'BOC-1352',marc:'Copeland',quantity:100,price:17.5,imageurl:'bocina/Copeland_bocina/1352_9R.jpg',model:'9R LADO MOTOR',flagmis:'no')
Product.create(name:'BEARING - PUMP SIDE STD MOD 9R.M',code:'BOC-1353',marc:'Copeland',quantity:100,price:17.0,imageurl:'bocina/Copeland_bocina/1353_9R.jpg',model:'9R.M LADO BOMBA',flagmis:'no')
Product.create(name:'BEARING - OVERSIZED MOD 3A,3R,E,L',code:'BOC-1546',marc:'Copeland',quantity:100,price:8.3,imageurl:'bocina/Copeland_bocina/1346_3R_3A_L_E_1546.jpg',model:'E,L,3A,3R',flagmis:'no')
Product.create(name:'BEARING - PUMP SIDE OVERSIZED 9R, THIN',code:'BOC-1553',marc:'Copeland',quantity:100,price:21.0,imageurl:'bocina/Copeland_bocina/1353_9R.jpg',model:'9R',flagmis:'no')
Product.create(name:'BEARING - PISTON SIDE STD MOD 3D',code:'BOC-2564',marc:'Copeland',quantity:100,price:1.0,imageurl:'bocina/Copeland_bocina/2464_3D.jpg',model:'3D LADO PISTON',flagmis:'no')
Product.create(name:'BEARING - PUMP SIDE STD MOD 3D',code:'BOC-2565',marc:'Copeland',quantity:100,price:24.08,imageurl:'bocina/Copeland_bocina/2464_3D.jpg',model:'3D LADO BOMBA',flagmis:'no')
Product.create(name:'BEARING - MOTOR SIDE STD MOD 3D',code:'BOC-2566',marc:'Copeland',quantity:100,price:23.75,imageurl:'bocina/Copeland_bocina/2464_3D.jpg',model:'3D LADO MOTOR',flagmis:'no')
Product.create(name:'BEARING - MOTOR SIDE STD MOD 4D/6D/4R/6R',code:'BOC-2567',marc:'Copeland',quantity:100,price:16.57,imageurl:'bocina/Copeland_bocina/2567_010_020_4D.jpg',model:'4D/6D/4R/6R LADO BOMBA',flagmis:'no')
Product.create(name:'BEARING - MOTOR SIDE STD MOD 4D/6D/4R/6R',code:'BOC-2568',marc:'Copeland',quantity:100,price:18.23,imageurl:'bocina/Copeland_bocina/2568_4D_6D_4R_6R_010_020.jpg',model:'4D/6D/4R/6R LADO MOTOR',flagmis:'no')
Product.create(name:'BEARING - MOTOR SIDE STD MOD 2D',code:'BOC-2594',marc:'Copeland',quantity:100,price:10.49,imageurl:'bocina/Copeland_bocina/2594_010_020_2D.jpg',model:'2D LADO MOTOR',flagmis:'no')
Product.create(name:'BEARING - CASE SIDE STD MOD 2D',code:'BOC-2595',marc:'Copeland',quantity:100,price:1.0,imageurl:'bocina/Copeland_bocina/2594_010_020_2D.jpg',model:'2D LADO CARCAZA',flagmis:'no')
Product.create(name:'BEARING - PUMP SIDE STD MOD 2D',code:'BOC-2596',marc:'Copeland',quantity:100,price:12.15,imageurl:'bocina/Copeland_bocina/2594_010_020_2D.jpg',model:'2D LADO BOMBA',flagmis:'no')
Product.create(name:'THREE-PHASE ELECTRIC PROTECTOR MOD L/E/N/9R',code:'COR-1505',marc:'Copeland',quantity:100,price:11.66,imageurl:'CORTA_CHISPA_COPELAND/COR-1505.gif',model:'vacio',flagmis:'no')
Product.create(name:'VALVE REED - DISCHARGE MOD 3AB,WB,4R,6R,L,M,N',code:'FLA-1502',marc:'Copeland',quantity:100,price:1.29,imageurl:'flappers/1502.jpg',model:'3AB,WB,4R,6R,L,M,N',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION KAT,KAL,KAK',code:'FLA-1503',marc:'Copeland',quantity:100,price:2.09,imageurl:'FLAPPER_COPELAN_PHOTO/FLA-1503.gif',model:'KAT,KAL,KAK',flagmis:'no')
Product.create(name:'VALVE REED - DISCHARGE E',code:'FLA-1506',marc:'Copeland',quantity:100,price:1.0,imageurl:'flappers/1506.jpg',model:'E',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION EAB,AD,AL,AV,RF',code:'FLA-1507',marc:'Copeland',quantity:100,price:3.64,imageurl:'FLAPPER_COPELAN_PHOTO/FLA-1507.gif',model:'EAB,AD,AL,AV,RF',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION MOD MRB,RC,4RL,RH,RK',code:'FLA-1525',marc:'Copeland',quantity:100,price:1.48,imageurl:'flappers/1525.jpg',model:'MRB,RC,4RL,RH,RK',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION MOD 3RK',code:'FLA-1580',marc:'Copeland',quantity:100,price:1.76,imageurl:'FLAPPER_COPELAN_PHOTO/FLA-1580.gif',model:'3RK',flagmis:'no')
Product.create(name:'VALVE REED - DISCHARGE MOD 3AJ/3AH/3RA/3RK',code:'FLA-1581',marc:'Copeland',quantity:100,price:1.66,imageurl:'FLAPPER_COPELAN_PHOTO/FLA-1581.gif',model:'3AJ/3AH/3RA/3RK',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION MOD 3AH/3AJ/3RA',code:'FLA-1582',marc:'Copeland',quantity:100,price:1.76,imageurl:'FLAPPER_COPELAN_PHOTO/FLA-1582.gif',model:'3AH/3AJ/3RA',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION MOD 9RS',code:'FLA-1583',marc:'Copeland',quantity:100,price:4.97,imageurl:'FLAPPER_COPELAN_PHOTO/FLA-1583.gif',model:'9RS',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION MOD KAE/KAG/KAM/KAN',code:'FLA-1584',marc:'Copeland',quantity:100,price:1.0,imageurl:'flappers/1584.jpg',model:'KAE/KAG/KAM/KAN',flagmis:'no')
Product.create(name:'VALVE REED - SUCTION MOD H',code:'FLA-1585',marc:'Copeland',quantity:100,price:1.5,imageurl:'FLAPPER_COPELAN_PHOTO/FLA-1585.gif',model:'H',flagmis:'no')
Product.create(name:'VALVE REED - DISCHARGE MOD H',code:'FLA-1586',marc:'Copeland',quantity:100,price:1.5,imageurl:'logo/no_dispo.jpg',model:'H',flagmis:'no')
Product.create(name:'VALVE REED - DISCHARGE MOD 4RR/6RR/4RT/4RJ/4RS/6RT/6RJ/8R',code:'FLA-2031',marc:'Copeland',quantity:100,price:2.21,imageurl:'logo/no_dispo.jpg',model:'4RR/6RR/4RT/4RJ/4RS/6RT/6RJ/8R',flagmis:'no')
Product.create(name:'BEARINGS KIT STD MOD NR',code:'KIT-1338',marc:'Copeland',quantity:100,price:35.0,imageurl:'kit_bocinas/1337_1338_1350.jpg',model:'. NR',flagmis:'no')
Product.create(name:'TERMINAL KIT MOD K/H',code:'KIT-5000',marc:'Copeland',quantity:100,price:12.0,imageurl:'KIT_DE_BOR_COPE_PHOTO/KIT-5000.gif',model:'K/H',flagmis:'no')
Product.create(name:'TERMINAL KIT MOD E/3A/3R',code:'KIT-5001',marc:'Copeland',quantity:100,price:22.6,imageurl:'KIT_DE_BOR_COPE_PHOTO/KIT-5001.gif',model:'E/3A/3R',flagmis:'no')
Product.create(name:'TERMINAL KIT MOD L/M',code:'KIT-5002',marc:'Copeland',quantity:100,price:17.32,imageurl:'logo/no_dispo.jpg',model:'L/M',flagmis:'no')
Product.create(name:'TERMINAL KIT  - NEW STYLE MOD 9R',code:'KIT-5003',marc:'Copeland',quantity:100,price:21.29,imageurl:'KIT_DE_BOR_COPE_PHOTO/KIT-5003.gif',model:'9R',flagmis:'no')
Product.create(name:'TERMINAL KIT MOD 4R/6R',code:'KIT-5005',marc:'Copeland',quantity:100,price:35.4,imageurl:'logo/no_dispo.jpg',model:'4R/6R',flagmis:'no')
Product.create(name:'TERMINAL KIT MOD 3D',code:'KIT-5006',marc:'Copeland',quantity:100,price:20.78,imageurl:'KIT_DE_BOR_COPE_PHOTO/KIT-5006.gif',model:'3D',flagmis:'no')
Product.create(name:'PISTON PIN MOD 4',code:'PAS-1519',marc:'Copeland',quantity:100,price:3.0,imageurl:'pasador/Copeland_pasador/1519.jpg',model:'4',flagmis:'no')
Product.create(name:'PISTON PIN MOD 2DD,DL,DA,3DB,DJ,MR',code:'PAS-1520',marc:'Copeland',quantity:100,price:3.0,imageurl:'pasador/Copeland_pasador/9575.jpg',model:'2DD,DL,DA,3DB,DJ,MR',flagmis:'no')
Product.create(name:'PISTON PIN MOD 6DG, DM,DN 4 & 6DG',code:'PAS-1523',marc:'Copeland',quantity:100,price:3.0,imageurl:'pasador/Copeland_pasador/9575.jpg',model:'6DG, DM,DN 4 Y 6DG',flagmis:'no')
Product.create(name:'PISTON PIN MOD H',code:'PAS-1569',marc:'Copeland',quantity:100,price:1.43,imageurl:'pasador/Copeland_pasador/9514.jpg',model:'H',flagmis:'no')
Product.create(name:'PISTON PIN MOD KAG/KAM/KAN/KAR',code:'PAS-9512',marc:'Copeland',quantity:100,price:1.0,imageurl:'pasador/Copeland_pasador/9512.jpg',model:'KAG/KAM/KAN/KAR',flagmis:'no')
Product.create(name:'PISTON PIN MOD KAJ/KAH/KAE',code:'PAS-9514',marc:'Copeland',quantity:100,price:1.43,imageurl:'pasador/Copeland_pasador/9514.jpg',model:'KAJ/KAH/KAE',flagmis:'no')
Product.create(name:'PISTON PIN MOD 9RA/NRN/RM/RB/RL/9RJ',code:'PAS-9516',marc:'Copeland',quantity:100,price:1.95,imageurl:'pasador/Copeland_pasador/9516.jpg',model:'9RA/NRN/RM/RB/RL/9RJ',flagmis:'no')
Product.create(name:'PISTON PIN MOD KAA/KAK/EAA/EAC',code:'PAS-9570',marc:'Copeland',quantity:100,price:1.59,imageurl:'pasador/Copeland_pasador/9570.jpg',model:'KAA/KAK/EAA/EAC',flagmis:'no')
Product.create(name:'PISTON PIN MOD 3AB/EAB/EAD/ERF/EAL/EAV/ERJ/EAJ/KAL/KAT',code:'PAS-9571',marc:'Copeland',quantity:100,price:1.59,imageurl:'pasador/Copeland_pasador/9571.jpg',model:'3AB/EAB/EAD/ERF/EAL/EAV/ERJ/EAJ/KAL/KAT',flagmis:'no')
Product.create(name:'PISTON PIN MOD 3RK/3AH/3AJ/3RA',code:'PAS-9575',marc:'Copeland',quantity:100,price:1.59,imageurl:'pasador/Copeland_pasador/9575.jpg',model:'3RK/3AH/3AJ/3RA',flagmis:'no')
Product.create(name:'PISTON PIN MOD MRG/L/9RB/9RC/9RP/RS/TL/NRA/RD/RE',code:'PAS-9577',marc:'Copeland',quantity:100,price:1.59,imageurl:'pasador/Copeland_pasador/9577.jpg',model:'MRG/L/9RB/9RC/9RP/RS/TL/NRA/RD/RE',flagmis:'no')
Product.create(name:'PISTON STD MOD 4',code:'PIS-2537',marc:'Copeland',quantity:100,price:18.0,imageurl:'NUEVOS_PISTONES_COPELAND/2537.gif',model:'4',flagmis:'no')
Product.create(name:'PISTON STD MOD KAG',code:'PIS-7021',marc:'Copeland',quantity:100,price:13.11,imageurl:'piston/Copeland_piston/KAH_KAG_KAE.jpg',model:'KAG',flagmis:'no')
Product.create(name:'PISTON STD MOD KAE',code:'PIS-7031',marc:'Copeland',quantity:100,price:13.11,imageurl:'piston/Copeland_piston/KAH_KAG_KAE.jpg',model:'KAE',flagmis:'no')
Product.create(name:'PISTON STD MOD KAA/KAK',code:'PIS-7061',marc:'Copeland',quantity:100,price:13.11,imageurl:'NUEVOS_PISTONES_COPELAND/PIS-7061.gif',model:'KAA/KAK',flagmis:'no')
Product.create(name:'PISTON STD MOD KAT',code:'PIS-7111',marc:'Copeland',quantity:100,price:14.73,imageurl:'NUEVOS_PISTONES_COPELAND/PIS-7111.gif',model:'KAT',flagmis:'no')
Product.create(name:'PISTON STD MOD ERF',code:'PIS-7131',marc:'Copeland',quantity:100,price:10.33,imageurl:'logo/no_dispo.jpg',model:'ERF',flagmis:'no')
Product.create(name:'PISTON STD MOD EAV/EAL',code:'PIS-7161',marc:'Copeland',quantity:100,price:14.5,imageurl:'piston/Copeland_piston/EAB_EAD_KAL_EAV_EAL.jpg',model:'EAV/EAL',flagmis:'no')
Product.create(name:'PISTON STD MOD LAH/NRB/NR40',code:'PIS-7231',marc:'Copeland',quantity:100,price:14.62,imageurl:'piston/Copeland_piston/7221_LAH_LAM_MRH_MRA_LAL_NRA_NRD_NRE_NRB_MRB_MRF.jpg',model:'LAH/NRB/NR40',flagmis:'no')
Product.create(name:'PISTON STD MOD LAC/NRA/NRD/NRE',code:'PIS-7261',marc:'Copeland',quantity:100,price:15.2,imageurl:'piston/Copeland_piston/7221_LAH_LAM_MRH_MRA_LAL_NRA_NRD_NRE_NRB_MRB_MRF.jpg',model:'LAC/NRA/NRD/NRE',flagmis:'no')
Product.create(name:'PISTON STD MOD 9RS3/RT/TH',code:'PIS-7281',marc:'Copeland',quantity:100,price:15.2,imageurl:'NUEVOS_PISTONES_COPELAND/PIS-7281.gif',model:'9RS3/RT/TH',flagmis:'no')
Product.create(name:'PISTON STD MOD 4RA/4RE/6RA/6RE/6RN/6RB',code:'PIS-7311',marc:'Copeland',quantity:100,price:1.0,imageurl:'NUEVOS_PISTONES_COPELAND/PIS-7311.gif',model:'4RA/4RE/6RA/6RE/6RN/6RB',flagmis:'no')
Product.create(name:'PISTON STD MOD 4',code:'PIS-7341',marc:'Copeland',quantity:100,price:19.0,imageurl:'NUEVOS_PISTONES_COPELAND/PIS-7341.gif',model:'4',flagmis:'no')
Product.create(name:'SERVICE VALVE 3/8',code:'VAL-2075',marc:'Copeland',quantity:100,price:15.44,imageurl:'NUEVAS_VALVULAS_COPELAND/VAL-2075.gif',model:'vacio',flagmis:'no')
Product.create(name:'SERVICE VALVE 1/2"',code:'VAL-2076',marc:'Copeland',quantity:100,price:16.14,imageurl:'NUEVAS_VALVULAS_COPELAND/VAL-2076.gif',model:'vacio',flagmis:'no')
Product.create(name:'SERVICE VALVE 5/8"',code:'VAL-2077',marc:'Copeland',quantity:100,price:16.84,imageurl:'NUEVAS_VALVULAS_COPELAND/VAL-2077.gif',model:'vacio',flagmis:'no')
